[bot_tokens]
Alpine = "Main Bot Token"
AlpineII = "Beta Bot Token"

[api_tokens]
DagpiAPI = "Dagpi API token for Image Cog"
TopGG = "TopGG API token"
TopGGWH = "Bot List Webhook Secret"
GitHub = "GitHub Access Token"
Roblox = "Roblox Token"
SpotifyClientID = "Spotify Client ID for Music Cog"
SpotifySecret = "Spotify Secret for Music Cog"

[postgresql]
host = "localhost"
port = 5432
user = "admin"
database = "alpine"

[webhooks]
join_log = "Webhook URL for join_log here
error_log = "Webhook URL for error_log here
request_log = "Webhook URL for request_log here
vote_log = "Webhook URL for vote_log here

[news]
news = "Why Hello There"