[bot_tokens]
Avimetry = "Stable Bot Token"
AvimetryII = "Beta Bot Token"

[api_tokens]
DagpiAPI = "Token for Dagpi API here"
TopGG = "Token for Top.GG API"
GitHub = "GitHub access token"

[postgresql]
host = "localhost"
port = 5432
user = "admin"
database = "avimetry"

[webhooks]
join_log = "Token for bot join logs here"
error_log = "Token for error logs here"
beta_error_log = "Token for beta bot error logs here"
request_log = "Token for requests here"

[news]
news = "PeePeeHead?!?"
