[bot_tokens]
    Avimetry = "Bot Token Here"

[api_tokens]
    DagpiAPI = "Dagpi token here"
    TopGG = "Top.gg token here"
    GitHub = "GitHub token here"

[postgresql]  
    host = "localhost"
    port = 5432
    user = "admin"
    database = "avimetry"

[webhooks]
    join_log = "Webhook for bot guild joins"
    error_log = "Webhook for bot errors"
    command_log = "Webhook for command logging"
    request_log = "Webhook for DM logging and `request` logging"

[news]
    news = "Please do not run your own instance of Avimetry."