[tool.black]
line-length = 125

[tool.isort]
profile = "black"
line_length = 125


[tool.pyright]
typeCheckingMode = "basic"

[tool.ruff]
select = ["E", "F"]
extend-ignore = ["F403"]
line-length = 125
dummy-variable-rgx = "^_$"